[package]
name = "zerust"
version = "0.1.0"
edition = "2024"
authors = ["wuzu zhao yitongwuzu1992@gmail.com"]
description = "Zero-cost Zinx for Rust"
license = "MIT"

[dependencies]
thiserror = "2.0.12"
dashmap = "7.0.0-rc2"
